-- MANUALLY CREATE EMPTY MATRIX DATABASE LOCALLY AND THAN USE BELOW

DROP TABLE IF EXISTS todoitems;

-- CREATING A 'TODOITEMS' TABLE IN 'MATRIX' DATABASE FOR APP PURPOSES
CREATE TABLE todoitems (
    id INT IDENTITY(1,1) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    deadline DATE,
    important BIT,
    completed BIT DEFAULT 0
);